### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'data'

### ISSUE THREAD

**Issue by broliao** [erikguo/yolov3#6]
**hi,thank you for your great work,when i run python3 train.py --spasity 0.0001,i get this erro,could you teach me how can I solve it,thanks a lot.**

Model Summary: 225 layers, 6.29987e+07 parameters, 457725 gradients

     Epoch   gpu_mem      GIoU       obj       cls     total   targets  img_size
  0%|                                                     | 0/4 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train_with_sparsity.py", line 390, in <module>
    train()  # transfer-learn yolo biases for 1 epoch
  File "train_with_sparsity.py", line 273, in train
    updateBN(opt.sparsity, model)
  File "train_with_sparsity.py", line 42, in updateBN
    m.weight.grad.data.add_(scale*torch.sign(m.weight.data))  # L1
AttributeError: 'NoneType' object has no attribute 'data'

**Comment by sammilei** [comment]
Hi, I encountered the same issue! Did you get it fixed?
